### ISSUE TITLE
my wife still left me please fix unplayable

### ISSUE THREAD

**Issue by halflife2isagoodgame** [Legofan0807/Klemmgine#3]
0/10 not elon musk approved

**Comment by Legofan0807** [comment]
planned fix in version 1.2

**Comment by halflife2isagoodgame** [comment]
fuck you then

**Comment by halflife2isagoodgame** [comment]
s

**Comment by halflife2isagoodgame** [comment]
a

**Comment by halflife2isagoodgame** [comment]
s

**Comment by halflife2isagoodgame** [comment]
s

**Comment by halflife2isagoodgame** [comment]
s

**Comment by halflife2isagoodgame** [comment]
s

**Comment by halflife2isagoodgame** [comment]
a

**Comment by halflife2isagoodgame** [comment]
<ay

**Comment by halflife2isagoodgame** [comment]
gay

**Comment by halflife2isagoodgame** [comment]
am,ogu
![image](https://user-images.githubusercontent.com/97802159/234354004-234a16a3-b8f8-41e7-a255-cf5ad0151840.png)

**Comment by halflife2isagoodgame** [comment]
a

**Comment by halflife2isagoodgame** [comment]
a

**Comment by halflife2isagoodgame** [comment]
finally! thank you :)

**Comment by halflife2isagoodgame** [comment]
a

**Comment by halflife2isagoodgame** [comment]
a

**Comment by halflife2isagoodgame** [comment]
a

**Comment by halflife2isagoodgame** [comment]
a

**Comment by halflife2isagoodgame** [comment]
a

**Comment by halflife2isagoodgame** [comment]
a

**Comment by halflife2isagoodgame** [comment]
a

**Comment by halflife2isagoodgame** [comment]
ya

**Comment by halflife2isagoodgame** [comment]
pls fix unplayable wife fucked my dad

**Comment by halflife2isagoodgame** [comment]
a

**Comment by halflife2isagoodgame** [comment]
a

**Comment by halflife2isagoodgame** [comment]
a

**Comment by halflife2isagoodgame** [comment]
a

**Comment by halflife2isagoodgame** [comment]
a

**Comment by halflife2isagoodgame** [comment]
wait this shoud fix it: printf ("pussy")

**Comment by halflife2isagoodgame** [comment]
shin megoomi tonsay

**Comment by Legofan0807** [comment]
L. you forgot the semicolon

**Comment by halflife2isagoodgame** [comment]
amogus sus
![image](https://user-images.githubusercontent.com/97802159/234354543-698fd0b4-d827-42a8-9c08-c8b77d8ad7a7.png)

**Comment by halflife2isagoodgame** [comment]
NOOOo

**Comment by halflife2isagoodgame** [comment]
sus amog;u

**Comment by halflife2isagoodgame** [comment]
idiot#3

**Comment by halflife2isagoodgame** [comment]
sus q0e09120u89rHAHAHAH

**Comment by halflife2isagoodgame** [comment]
YAHAHAHA

**Comment by halflife2isagoodgame** [comment]
![image](https://user-images.githubusercontent.com/97802159/234354805-440722bb-8ab8-4c00-828e-45616fcf3d62.png)
YAHAHA

**Comment by halflife2isagoodgame** [comment]
**BUSSY**

**Comment by halflife2isagoodgame** [comment]
### **BNUSSY**

**Comment by halflife2isagoodgame** [comment]
### **SUSSS**

**Comment by Legofan0807** [comment]
What the fuck did you just fucking say about me, you little bitch? I'll have you know I graduated top of my class in the Navy Seals, and I've been involved in numerous secret raids on Al-Quaeda, and I have over 300 confirmed kills. I am trained in gorilla warfare and I'm the top sniper in the entire US armed forces. You are nothing to me but just another target. I will wipe you the fuck out with precision the likes of which has never been seen before on this Earth, mark my fucking words. You think you can get away with saying that shit to me over the Internet? Think again, fucker. As we speak I am contacting my secret network of spies across the USA and your IP is being traced right now so you better prepare for the storm, maggot. The storm that wipes out the pathetic little thing you call your life. You're fucking dead, kid. I can be anywhere, anytime, and I can kill you in over seven hundred ways, and that's just with my bare hands. Not only am I extensively trained in unarmed combat, but I have access to the entire arsenal of the United States Marine Corps and I will use it to its full extent to wipe your miserable ass off the face of the continent, you little shit. If only you could have known what unholy retribution your little "clever" comment was about to bring down upon you, maybe you would have held your fucking tongue. But you couldn't, you didn't, and now you're paying the price, you goddamn idiot. I will shit fury all over you and you will drown in it. You're fucking dead, kiddo.

**Comment by halflife2isagoodgame** [comment]
can we honestly e date? you’re so beautiful. You always make me laugh, you always make me smile. You literally make me want to become a better person... I really enjoy every moment we spend together. My time has no value unless its spent with you. I tell everyone of my irls how awesome you are. Thank you for being you. Whenever you need someone to be there for you, know that i’ll always be right there by your side. I love you so much. I don’t think you ever realize how amazing you are sometimes. Life isn’t as fun when you’re not around. You are truly stunning. I want you to be my soulmate. I love the way you smile, your eyes are absolutely gorgeous. If I had a star for everytime you crossed my mind i could make the entire galaxy. Your personality is as pretty as you are and thats saying something. I love you, please date me. I am not even calling it e dating anymore because I know we will meet soon enough heart OK I ADMIT IT I LOVE YOU OK i hecking love you and it breaks my heart when i see you play with someone else or anyone commenting in your profile i just want to be your girlfriend and put a heart in my profile linking to your profile and have a walltext of you commenting cute things i want to play video games talk in discord all night and watch a movie together but you just seem so uninsterested in me it hecking kills me and i cant take it anymore i want to remove you but i care too much about you so please i’m begging you to eaither love me back or remove me and never contact me again it hurts so much to say this because i need you by my side but if you dont love me then i want you to leave because seeing your icon in my friendlist would kill me everyday of my pathetic life.
